name: Publish

on:
  workflow_call:
  release:
    types: [published]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: ğŸ“¦ Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          bun install --frozen-lockfile
          bun run build
      - name: ğŸš€ Publish
        if: ${{ steps.release.outputs.release_created }}
        run: bun publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}